language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
before_install:
    - pip install --upgrade pytest pytest-cov coveralls bibtexparser
install:
    - python setup.py develop
script:
    - py.test
after_success:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
          coveralls;
      fi
